[build]
  command = "npm run build"
  publish = ".next"

# Configure secrets scanning to ignore public environment variables
# These are intentionally public (NEXT_PUBLIC_* variables are bundled into client code)
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_URL"

